import mysql.connector
import os
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

db_config = {
    'host': 'localhost',
    'user': 'root',
    'password': os.getenv('DB_PASSWORD'),
    'database': 'navadisha'
}

def save_to_db(problem, response, citations):
    """
    Saves interaction logs. 
    The 'id' and 'timestamp' are handled automatically by MySQL.
    """
    try:
        conn = mysql.connector.connect(**db_config)
        cursor = conn.cursor()
        
        # INSERT ignores 'id' and 'timestamp' because they are auto-generated
        query = """
            INSERT INTO queries_navadisha (problem, response, source_citations) 
            VALUES (%s, %s, %s)
        """
        
        cursor.execute(query, (problem, response, citations))
        
        conn.commit()
        cursor.close()
        conn.close()
        print("Data saved successfully (ID auto-generated by DB)!")
        
    except mysql.connector.Error as err:
        print(f"Database error: {err}")